# 🧩 Nombre y puerto
spring.application.name=gimnasio
server.port=${PORT:8080}   # 👈 necesario para Railway (usa variable PORT)

# 🔥 Firebase (RTDB)
firebase.database.url=https://gimnasio-58f2c-default-rtdb.firebaseio.com
firebase.credentials.path=classpath:gimnasio-58f2c-firebase-adminsdk-fbsvc-72b58ecc5c.json

# 🌐 Configuración de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# 🧱 Logs más claros (útil en producción)
logging.level.org.springframework.security=INFO
logging.level.com.energia_y_salud_web.security=INFO

# 🔐 (Opcional) Token JWT - ejemplo
jwt.secret=${JWT_SECRET:mi_clave_secreta}
jwt.expiration=86400000